-- Create pool_data table for temperature history
CREATE TABLE IF NOT EXISTS public.pool_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    temp_value double precision NOT NULL,
    relay_status boolean DEFAULT false
);

-- Create pool_config table for automation settings
CREATE TABLE IF NOT EXISTS public.pool_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone,
    temp_on double precision DEFAULT 28.0,
    temp_off double precision DEFAULT 30.0
);

-- Insert default config if not exists
INSERT INTO public.pool_config (id, temp_on, temp_off)
SELECT 1, 28.0, 30.0
WHERE NOT EXISTS (SELECT 1 FROM public.pool_config WHERE id = 1);

-- Enable Realtime for these tables
alter publication supabase_realtime add table pool_data;
alter publication supabase_realtime add table pool_config;
