-- Create devices table
CREATE TABLE IF NOT EXISTS public.devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('cooling', 'heating')),
    icon text -- store lucide icon name or similar identifier
);

-- Seed devices
INSERT INTO public.devices (name, type, icon) VALUES
('Balcão Frente (Portas 1,2)', 'cooling', 'Refrigerator'),
('Balcão Frente (Portas 3,4)', 'cooling', 'Refrigerator'),
('Balcão Frente (Portas 5,6)', 'cooling', 'Refrigerator'),
('Balcão Cozinha', 'cooling', 'Refrigerator'),
('Freezer Cozinha', 'cooling', 'Snowflake'),
('Freezer Frente', 'cooling', 'Snowflake'),
('Expositor Coca-Cola', 'cooling', 'GlassWater'),
('Expositor Ibera', 'cooling', 'Beer'),
('Estufa Salgados', 'heating', 'Croissant');

-- Create device_readings table (replaces pool_data)
CREATE TABLE IF NOT EXISTS public.device_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    device_id bigint REFERENCES public.devices(id) NOT NULL,
    temp_value double precision NOT NULL,
    actuator_status boolean DEFAULT false -- Status of Compressor or Resistance
);

-- Create device_settings table (replaces pool_config)
CREATE TABLE IF NOT EXISTS public.device_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone,
    device_id bigint REFERENCES public.devices(id) NOT NULL UNIQUE,
    temp_on double precision NOT NULL,
    temp_off double precision NOT NULL
);

-- Initialize default settings for all devices
-- Cooling: On at 4, Off at 2 (Example default)
-- Heating: On at 60, Off at 65 (Example default)
INSERT INTO public.device_settings (device_id, temp_on, temp_off)
SELECT id, 
       CASE WHEN type = 'cooling' THEN 4.0 ELSE 60.0 END,
       CASE WHEN type = 'cooling' THEN 2.0 ELSE 65.0 END
FROM public.devices;

-- Enable Realtime
alter publication supabase_realtime add table device_readings;
alter publication supabase_realtime add table device_settings;
